apiVersion: v2
name: argoplane
description: A package of ArgoCD UI extensions
type: application
version: 1.4.1
appVersion: "1.4.1"
home: https://argoplane.io
annotations:
  artifacthub.io/license: Apache-2.0
sources:
  - https://github.com/natrontech/argoplane
maintainers:
  - name: Natron Tech AG
    email: info@natron.io
    url: https://natron.io
keywords:
  - argocd
  - extensions
  - platform-engineering
  - kubernetes
  - metrics
  - backups
  - networking
icon: https://argoplane.io/logo.svg
